name: lutris
base: core22
adopt-info: lutris
grade: stable
confinement: strict
compression: lzo
license: GPL-3.0-only
source-code: https://git.launchpad.net/lutris-snap/tree/snapcraft.yaml
issues:
  - https://github.com/sameersharma2006/lutris-snap/issues
  - https://bugs.launchpad.net/lutris-snap
architectures:
  - build-on: amd64

assumes:
  - snapd2.60

lint:
  ignore:
    - classic
    - library:
      - usr/*

package-repositories:
  - type: apt
    formats: [deb]
    architectures: [i386]
    components: [main]
    suites: [jammy]
    key-id: F23C5A6CF475977595C89F51BA6932366A755776
    url: https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu

layout:
  /usr/bin/vkcube:
    symlink: $SNAP/usr/bin/vkcube
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan
  /usr/lib/$CRAFT_ARCH_TRIPLET/libvkd3d.so.1.1.0:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libvkd3d.so.1.1.0
  /usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_intel_hasvk.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_intel_hasvk.so
  /usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_lvp.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_lvp.so
  /usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_radeon.so
  /usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_virtio.so:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan_virtio.so
  /usr/lib/p7zip:
    symlink: $SNAP/usr/lib/p7zip

apps:
  lutris:
    command: usr/bin/lutris
    extensions: [gnome]
    environment:
      APPIMAGE_EXTRACT_AND_RUN: 1
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages
      DISABLE_WAYLAND: 1
    common-id: net.lutris.Lutris
    desktop: usr/share/applications/net.lutris.Lutris.desktop
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-record
      - audio-playback
      - bluez
      - joystick
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - upower-observe

slots:
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris

parts:
  lutris:
    source: https://github.com/lutris/lutris.git
    source-tag: 'v0.5.17'
    source-depth: 1
    plugin: meson
    parse-info: [usr/share/metainfo/net.lutris.Lutris.metainfo.xml]
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      craftctl default
      sed -e 's|Icon=lutris|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/lutris.svg|' -i  share/applications/net.lutris.Lutris.desktop

  deps:
    after: [lutris]
    plugin: nil
    stage-packages:
      - psmisc
      - cabextract
      - unzip
      - p7zip-full
      - p7zip-rar
      - curl
      - fluid-soundfont-gs
      - pciutils
      - libpci3
      - mesa-vulkan-drivers
      - vulkan-tools
      - libvulkan1
      - libvkd3d1
    prime:
      - bin/fuser
      - usr/bin/killall
      - usr/bin/peekfd
      - usr/bin/prtstat
      - usr/bin/pslog
      - usr/bin/pstree
      - usr/share/menu/psmisc
      - usr/share/pixmaps/pstree16.xpm
      - usr/share/pixmaps/pstree32.xpm
      - usr/bin/cabextract
      - usr/share/icons/cab_extract.png
      - usr/share/icons/cab_view.png
      - usr/bin/funzip
      - usr/bin/unzip
      - usr/bin/unzipsfx
      - usr/bin/zipgrep
      - usr/bin/zipinfo
      - usr/lib/mime/packages/unzip
      - usr/bin/7z*
      - usr/lib/p7zip
      - usr/bin/curl
      - usr/share/zsh/vendor-completions/_curl
      - usr/share/sounds/sf2/FluidR3_GS.sf2
      - usr/bin/lspci
      - usr/bin/setpci
      - usr/sbin/update-pciids
      - usr/lib/*/libpci*
      - usr/bin/vk*
      - usr/bin/vulkaninfo
      - usr/share/vulkan
      - usr/bin/mesa*
      - usr/lib/*/libVk*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libvkd3d*
      - usr/share/drirc.d

  py-deps:
    after: [deps]
    plugin: nil
    stage-packages:
      - python3-pil
      - python3-distro
      - python3-requests
      - python3-protobuf
      - python3-lxml
      - python3-yaml
      - python3-gi
      - python3-gi-cairo
      - python3-setproctitle
      - python3-magic
      - python3-dbus
      - python3-evdev
    prime:
      - usr/lib/python3

  tls:
    after: [py-deps]
    plugin: nil
    stage-packages:
      - libgnutls30:i386
    prime:
      - usr/lib

  vetus:
    after: [tls]
    plugin: nil
    stage-packages:
      - libxcb1:i386
      - libgl1:i386
      - libvulkan1:i386
    prime:
      - usr/lib/*/libxcb*
      - usr/lib/*/libX*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libGL*

  sundry:
    after: [vetus]
    plugin: nil
    stage-packages:
      - libfaudio0
      - libpcap0.8
      - ocl-icd-libopencl1
      - libopenal1
      - libgphoto2-port12
      - libgphoto2-6
      - libprotobuf23
      - libraqm0
      - libimagequant0
      - libinih1
      - libsdl2-2.0-0
      - libmspack0
      - libstb0
      - libdecor-0-0
      - libxss1
      - libsndio7.0
      - libexif12
      - libinstpatch-1.0-2
      - libusb-1.0-0
      - libmagic1
      - x11-xserver-utils
      - mesa-utils-bin
      - mesa-utils
      - kitty
      - libxcb1
    prime:
      - usr/lib/*/libmspack*
      - usr/lib/*/libSDL2*
      - usr/lib/*/libinih*
      - usr/lib/*/libimagequant*
      - usr/lib/*/libraqm*
      - usr/lib/*/libprotobuf*
      - lib/udev
      - usr/lib/*/libgphoto2*
      - usr/lib/*/libopenal*
      - usr/lib/*/libpcap*
      - usr/lib/*/libFAudio*
      - usr/lib/*/libOpenCL*
      - usr/lib/*/libstb*
      - usr/lib/*/libdecor*
      - usr/lib/*/libXss*
      - usr/lib/*/libsndio*
      - usr/lib/*/libexif*
      - usr/lib/*/libinstpatch*
      - usr/lib/*/libusb*
      - usr/lib/*/libmagic*
      - usr/bin/xrandr
      - usr/bin/glx*
      - usr/bin/es2*
      - usr/bin/egl*
      - usr/share/mesa-demos
      - usr/bin/kitty
      - usr/lib/*/libxcb*
      - usr/lib/*/libXau*
      - usr/lib/*/libXdmcp*
      - usr/lib/*/libbsd*
      - usr/lib/*/libmd*

  wine-deps:
    after: [sundry]
    plugin: nil
    stage-packages:
      - winetricks
      - wine
    prime:
      - usr/lib/*/wine
      - usr/share/wine
      - usr/bin/winetricks
      - usr/share/bash-completion/completions/winetricks
      - usr/share/icons/hicolor/scalable/apps/winetricks.svg
      - usr/lib/wine
      - usr/bin/wine-stable
      
  fluidsynth:
    after: [wine-deps]
    plugin: nil
    stage-packages:
      - fluidsynth
    
  gamemode:
    after: [wine-deps]
    plugin: nil
    stage-packages:
      - gamemode
      
  cleanup:
    after: [gamemode]
    plugin: nil
    build-snaps:
      - gnome-42-2204
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
